# permissions for end users to edit demodeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demodeployment-editor-role
rules:
- apiGroups:
  - scale.mstrielnikov
  resources:
  - demodeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.mstrielnikov
  resources:
  - demodeployments/status
  verbs:
  - get
